# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-02-14 14:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250)),
                ('summary', models.CharField(blank=True, max_length=130, null=True)),
                ('content', models.CharField(max_length=2500)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('image', models.FileField(blank=True, null=True, upload_to='internal_posts/', verbose_name="Photo d'illustration")),
            ],
        ),
    ]
