# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-02-22 10:23
from __future__ import unicode_literals

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_auto_20180214_1541'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sitecontent',
            name='content',
        ),
        migrations.AddField(
            model_name='sitecontent',
            name='content_left',
            field=ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='Texte de gauche'),
        ),
        migrations.AddField(
            model_name='sitecontent',
            name='content_right',
            field=ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='Texte de droite'),
        ),
    ]
